### ISSUE TITLE
Game::LCP::initializeNotProcessed is inefficient

### ISSUE THREAD

**Issue by ssriram1992** [ssriram1992/EPECsolve#29]
The function `Game::LCP::initializeNotProcessed` which initializes the set of all (exponentially many) unprocessed polyhedra is super-inefficient for even slightly large problems.

Can we have a work-around for this? For example, if we are going to use some algorithm (i.e., our inner approximation, but with the random selection of polyhedron), can we avoid using this function?

**Comment by gdragotto** [comment]
A possible fix is committed in a226652. To be tested!

**Comment by gdragotto** [comment]
835f750 fixed some issues with the last commit.
