### ISSUE TITLE
`using namespace something;`

### ISSUE THREAD

**Issue by ssriram1992** [ssriram1992/EPECsolve#32]
Please refrain from using namespace something in a header file. 
It brings the specific namespace to global namespace for the user also, thus defeating the whole purpose of namespaces at all!
 I saw multiple places with 

- `using namespace std;` 
- `using namespace Game'` 

etc. Please remove all such usages. For example, you should not have been able to write `vector<short int> encoding;` in include/algorithms/outerapproximation.h.

**Comment by gdragotto** [comment]
Sure. It's again because of code consistency with the old codebase.

**Comment by ssriram1992** [comment]
What code consistency, sorry? The old one did not have any `using namespace something` in the headers? They were, if at all, only in .cpp files (which is okay now too).

**Comment by gdragotto** [comment]
For better code readability, fixed in 52f1445.
