### ISSUE TITLE
Documentation for outerApproximation

### ISSUE THREAD

**Issue by ssriram1992** [ssriram1992/EPECsolve#33]
Please document functions as you write them. I find a large part of the code undocumented. For example the `class Tree`. 

Some documentation templates also seem to be wrong - what should be description of a class/constructor falls in one of the members, and many members in the new headers are undocumented. 

We should be able to compile the doxygen documentation, i.e., do `make docDetailed` and be able to generate the complete documentation.

**Comment by gdragotto** [comment]
The documentation will be completed as soon as a working commit is pushed. The one you have right now is a sketch
